name: 'Setup GAP for package testing'
description: 'Download and compile CI scripts, GAP and its packages'
inputs:
  GAP_PKGS_TO_CLONE:
    description: 'the GAP packages to clone'
    required: false
    default: ''
  GAP_PKGS_TO_BUILD:
    description: 'the GAP packages to build'
    required: false
    default: 'io profiling'
  GAPBRANCH:
    description: 'the gap branch to clone'
    required: false
    default: 'master'
  HPCGAP:
    description: 'build HPC-GAP if set to yes'
    required: false
    default: 'no'
  ABI:
    description: 'set to 32 to use 32bit build flags for the package'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
      - name: "Download CI scripts"
        run:  git clone https://github.com/gap-system/pkg-ci-scripts.git
        shell: bash
      - name: "Compile GAP and download packages"
        run:  pkg-ci-scripts/build_gap.sh
        env:
          GAP_PKGS_TO_CLONE: ${{ inputs.GAP_PKGS_TO_CLONE }}
          GAP_PKGS_TO_BUILD: ${{ inputs.GAP_PKGS_TO_BUILD }}
          GAPBRANCH: ${{ inputs.GAPBRANCH }}
          HPCGAP: ${{ inputs.HPCGAP }}
        shell: bash
      - name: "If package is to be built in 32bit, install dependencies"
        run: |
          if [ ${{inputs.ABI}} = '32' ]
          then
            packages=(
              libgmp-dev:i386
              libreadline-dev:i386
              zlib1g-dev:i386
              gcc-multilib
              g++-multilib
            )
            sudo apt-get install "${packages[@]}"
          fi
        shell: bash
      - name: "Prepare the package"
        run:  pkg-ci-scripts/build_pkg.sh
        env:
          ABI: ${{ inputs.ABI }}
        shell: bash
      - run: ${{ github.action_path }}/goodbye.sh
        shell: bash
